### ISSUE TITLE
adb与模拟器可以正常链接但检测不到游戏

### ISSUE THREAD

**Issue by citrusreticulata** [sanmusen214/BAAH#17]
adb与模拟器可以正常链接但检测不到游戏，运行日志如下：
```
08-Jan-24 19:58:42 - INFO - 启动模拟器
08-Jan-24 19:58:42 - INFO - 等待1...
08-Jan-24 19:58:45 - INFO - 等待2...
08-Jan-24 19:58:48 - INFO - 等待3...
08-Jan-24 19:58:51 - INFO - 检查连接1/5...
08-Jan-24 19:58:51 - INFO - 删除c5fd3201.png
截图文件大小为 654.1845703125 KB
08-Jan-24 19:58:53 - INFO - adb与模拟器连接正常
08-Jan-24 19:58:53 - INFO - 图片分辨率为1280*720
08-Jan-24 19:58:55 - INFO - 打开游戏...
08-Jan-24 19:58:58 - INFO - 当前运行的app为：  mCurrentFocus=null
08-Jan-24 19:58:58 - INFO - 检测到游戏未打开，尝试打开游戏...
08-Jan-24 19:59:05 - INFO - 打开游戏...
08-Jan-24 19:59:09 - INFO - 当前运行的app为：  mCurrentFocus=null
08-Jan-24 19:59:09 - INFO - 检测到游戏未打开，尝试打开游戏...
08-Jan-24 19:59:16 - INFO - 打开游戏...
08-Jan-24 19:59:19 - INFO - 当前运行的app为：  mCurrentFocus=null
连接后多次打开失败，是否重启adb服务或跳过？(y/n/k):
```
当时的状态是，能看到模拟器里面游戏已经正常打开了，但是脚本运行卡在找不到app，如上面的日志所示。
版本号是1.1.13，之前正常使用过一段时间现在突然不行了

**Comment by citrusreticulata** [comment]
更新到1.1.14依旧还是这个问题：
```
读取E:\游戏文档\Blue Archive 碧蓝档案\自动脚本\BAAH1.1.14\config.json文件成功, 读取了25个配置
2024-01-08 20:21:28.0912134 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
08-Jan-24 20:21:28 - INFO - 读取默认config文件: config.json
读取E:\游戏文档\Blue Archive 碧蓝档案\自动脚本\BAAH1.1.14\config.json文件成功, 读取了25个配置
08-Jan-24 20:21:28 - INFO - 重新读取指定的config文件: config.json
08-Jan-24 20:21:28 - INFO - 模拟器:D:/software/MuMu/MuMuPlayer-12.0/shell/MuMuPlayer.exe
08-Jan-24 20:21:28 - INFO - 端口:7555
+======================================BAAH====================================== +
||                                Version: 1.1.14                                 ||
||                  Bilibili: https://space.bilibili.com/7331920                  ||
||                  Github: https://github.com/sanmusen214/BAAH                   ||
||                                 QQ群: 441069156                                 ||
||                                                                                ||
+================================================================================+
08-Jan-24 20:21:28 - INFO - 启动模拟器
08-Jan-24 20:21:28 - INFO - 等待1...
08-Jan-24 20:21:31 - INFO - 等待2...
08-Jan-24 20:21:34 - INFO - 等待3...
08-Jan-24 20:21:39 - INFO - 检查连接1/7...
08-Jan-24 20:21:39 - INFO - 删除c5fd3201.png
截图文件大小为 1091.9345703125 KB
08-Jan-24 20:21:42 - INFO - adb与模拟器连接正常
08-Jan-24 20:21:42 - INFO - 图片分辨率为1280*720
08-Jan-24 20:21:44 - INFO - 打开游戏...
08-Jan-24 20:21:47 - INFO - 当前运行的app为：  mCurrentFocus=null
08-Jan-24 20:21:47 - INFO - 检测到游戏未打开，尝试打开游戏...
08-Jan-24 20:21:54 - INFO - 打开游戏...
08-Jan-24 20:21:57 - INFO - 当前运行的app为：  mCurrentFocus=null
08-Jan-24 20:21:57 - INFO - 检测到游戏未打开，尝试打开游戏...
08-Jan-24 20:22:04 - INFO - 打开游戏...
08-Jan-24 20:22:07 - INFO - 当前运行的app为：  mCurrentFocus=null
连接后多次打开失败，是否重启adb服务或跳过？(y/n/k):
```

**Comment by citrusreticulata** [comment]
更奇怪的是BAAH能正常在模拟器里面打开游戏，但就是连不上。游戏是国际版的

**Comment by citrusreticulata** [comment]
我试了下本地直接运行源码，也有这个问题，但这次没有`onnxruntime`的报错了。
```cmd
(BAAH) E:\游戏文档\Blue Archive 碧蓝档案\自动脚本\源码\BAAH-BAAH1.1.14>python ./main.py
读取E:\游戏文档\Blue Archive 碧蓝档案\自动脚本\源码\BAAH-BAAH1.1.14\config.json文件成功, 读取了36个配置
08-Jan-24 20:52:25 - INFO - 读取默认config文件: config.json
08-Jan-24 20:52:25 - INFO - 模拟器:D:/Software/MuMuPlayer-12.0/shell/MuMuPlayer.exe
08-Jan-24 20:52:25 - INFO - 端口:16384
+======================================BAAH====================================== +
||                                Version: 1.1.14                                 ||
||                  Bilibili: https://space.bilibili.com/7331920                  ||
||                  Github: https://github.com/sanmusen214/BAAH                   ||
||                                 QQ群: 441069156                                 ||
||                                                                                ||
+================================================================================+
08-Jan-24 20:52:25 - INFO - 启动模拟器
08-Jan-24 20:52:25 - ERROR - 启动模拟器失败, 可能是没有以管理员模式运行 或 配置的模拟器路径有误
08-Jan-24 20:52:25 - WARNING - 检查是否能够建立与模拟器的连接...
08-Jan-24 20:52:27 - INFO - 检查连接1/7...
截图文件大小为 533.14453125 KB
08-Jan-24 20:52:30 - INFO - adb与模拟器连接正常
08-Jan-24 20:52:30 - INFO - 图片分辨率为1280*720
08-Jan-24 20:52:32 - INFO - 打开游戏...
08-Jan-24 20:52:35 - INFO - 当前运行的app为：  mCurrentFocus=null
08-Jan-24 20:52:35 - INFO - 检测到游戏未打开，尝试打开游戏...
08-Jan-24 20:52:42 - INFO - 打开游戏...
08-Jan-24 20:52:45 - INFO - 当前运行的app为：  mCurrentFocus=null
08-Jan-24 20:52:45 - INFO - 检测到游戏未打开，尝试打开游戏...
08-Jan-24 20:52:52 - INFO - 打开游戏...
08-Jan-24 20:52:55 - INFO - 当前运行的app为：  mCurrentFocus=null
连接后多次打开失败，是否重启adb服务或跳过？(y/n/k):Traceback (most recent call last):
  File "E:\游戏文档\Blue Archive 碧蓝档案\自动脚本\源码\BAAH-BAAH1.1.14\main.py", line 44, in <module>
    BAAH_main()
  File "E:\游戏文档\Blue Archive 碧蓝档案\自动脚本\源码\BAAH-BAAH1.1.14\BAAH.py", line 45, in BAAH_main
    yorn = input("连接后多次打开失败，是否重启adb服务或跳过？(y/n/k):")
KeyboardInterrupt
^C
```
还有，老哥你是不是没把`tools`文件夹放到项目里，我本地打包是缺失文件的

**Comment by citrusreticulata** [comment]
我今天又测试了一下不同系统，在两台不同的电脑上分别测了一下，我在windows11和windows10都试了一下都出现这个问题了，看来应该不是系统的问题？

**Comment by sanmusen214** [comment]
Mumu模拟器需要按照文档教程里关闭后台保活，[常见问题](https://docs.qq.com/doc/DR1RPaURleGF0ZWFS)

**Comment by citrusreticulata** [comment]
有道理，解决了！非常感谢！@sanmusen214
