### ISSUE TITLE
7-1困难, 自动推图报错

### ISSUE THREAD

**Issue by YatsukiRenka** [sanmusen214/BAAH#29]
![image](https://github.com/sanmusen214/BAAH/assets/38554950/f9c2214f-694e-4843-837c-f4a085c7faa5)

```bash
09-Mar-24 22:45:55 - INFO - 分割后的关卡序号：['7', '1']
09-Mar-24 22:45:55 - INFO - 格子关卡：7-1，开始推图
09-Mar-24 22:45:55 - INFO - 识别到S标签，判断为走格子战斗
09-Mar-24 22:45:58 - WARNING - 试图点击的目标图像不存在: ./DATA/assets_jp/BUTTON/BUTTON_TASK_START.png
09-Mar-24 22:46:00 - INFO - 判断任务GridQuest是否可以执行
09-Mar-24 22:46:02 - INFO - 执行任务GridQuest
09-Mar-24 22:46:02 - INFO - 成功读取关卡文件H7-1.json，开始执行
09-Mar-24 22:46:02 - INFO - 使用上次的队伍配置:
09-Mar-24 22:46:03 - INFO - 配置队伍A
09-Mar-24 22:46:07 - INFO - 点击出击
09-Mar-24 22:46:12 - INFO - 配置队伍B
09-Mar-24 22:46:14 - INFO - 点击出击
09-Mar-24 22:46:20 - INFO - 开始战斗！
09-Mar-24 22:46:24 - INFO - 判断是否需要设置自动战斗开启和PHASE自动结束关闭
09-Mar-24 22:46:25 - INFO - ocr结果1
09-Mar-24 22:46:25 - INFO - 当前聚焦队伍A
09-Mar-24 22:46:25 - INFO - 执行step:0 action:0 队伍A->move left-up
09-Mar-24 22:46:26 - INFO - 点击[648, 225]
09-Mar-24 22:46:27 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:46:28 - INFO - 尝试呼出弹窗
09-Mar-24 22:46:35 - INFO - 尝试清空弹窗
09-Mar-24 22:46:37 - INFO - ocr结果2
09-Mar-24 22:46:37 - INFO - 当前聚焦队伍B
09-Mar-24 22:46:37 - INFO - 执行step:0 action:1 队伍B->move left
09-Mar-24 22:46:39 - INFO - 点击[579, 488]
09-Mar-24 22:46:40 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:46:40 - INFO - 尝试呼出弹窗
09-Mar-24 22:46:43 - INFO - 尝试清空弹窗
09-Mar-24 22:46:45 - INFO - PHASE结束
09-Mar-24 22:46:48 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:46:48 - INFO - 尝试呼出弹窗
09-Mar-24 22:46:57 - INFO - 尝试清空弹窗
09-Mar-24 22:46:59 - INFO - ocr结果1
09-Mar-24 22:47:01 - INFO - ocr结果2
09-Mar-24 22:47:01 - INFO - 当前聚焦队伍B
09-Mar-24 22:47:01 - INFO - 执行step:1 action:0 队伍B->portal left
09-Mar-24 22:47:03 - INFO - 点击[989, 770]
09-Mar-24 22:47:06 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:47:06 - INFO - 尝试呼出弹窗
09-Mar-24 22:47:09 - INFO - 尝试清空弹窗
09-Mar-24 22:47:11 - INFO - ocr结果2
09-Mar-24 22:47:13 - INFO - ocr结果1
09-Mar-24 22:47:13 - INFO - 当前聚焦队伍A
09-Mar-24 22:47:13 - INFO - 执行step:1 action:1 队伍A->exchange left-down
09-Mar-24 22:47:14 - INFO - 点击[614, 351]
09-Mar-24 22:47:18 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:47:20 - INFO - 尝试呼出弹窗
09-Mar-24 22:47:23 - INFO - 尝试清空弹窗
09-Mar-24 22:47:25 - INFO - ocr结果2
09-Mar-24 22:47:27 - INFO - ocr结果1
09-Mar-24 22:47:27 - INFO - 当前聚焦队伍A
09-Mar-24 22:47:27 - INFO - 执行step:1 action:2 队伍A->portal center
09-Mar-24 22:47:28 - INFO - 点击[1104, 770]
09-Mar-24 22:47:32 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:47:32 - INFO - 尝试呼出弹窗
09-Mar-24 22:47:34 - INFO - 尝试清空弹窗
09-Mar-24 22:47:37 - INFO - ocr结果1
09-Mar-24 22:47:37 - INFO - 当前聚焦队伍A
09-Mar-24 22:47:37 - INFO - 执行step:1 action:3 队伍A->move left-up
09-Mar-24 22:47:39 - INFO - 点击[1044, 690]
09-Mar-24 22:47:40 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:47:42 - INFO - 尝试呼出弹窗
09-Mar-24 22:47:45 - INFO - 尝试清空弹窗
09-Mar-24 22:47:47 - INFO - PHASE结束
09-Mar-24 22:47:52 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:47:52 - INFO - 尝试呼出弹窗
09-Mar-24 22:47:55 - INFO - 尝试清空弹窗
09-Mar-24 22:47:57 - INFO - ocr结果1
09-Mar-24 22:47:59 - INFO - ocr结果2
09-Mar-24 22:47:59 - INFO - 当前聚焦队伍B
09-Mar-24 22:47:59 - INFO - 执行step:2 action:0 队伍B->move left
09-Mar-24 22:48:00 - INFO - 点击[989, 770]
09-Mar-24 22:48:01 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:48:02 - INFO - 尝试呼出弹窗
09-Mar-24 22:48:04 - INFO - 尝试清空弹窗
09-Mar-24 22:48:06 - INFO - PHASE结束
09-Mar-24 22:48:11 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:48:11 - INFO - 尝试呼出弹窗
09-Mar-24 22:48:14 - INFO - 尝试清空弹窗
09-Mar-24 22:48:16 - INFO - ocr结果1
09-Mar-24 22:48:18 - INFO - ocr结果2
09-Mar-24 22:48:18 - INFO - 当前聚焦队伍B
09-Mar-24 22:48:18 - INFO - 执行step:3 action:0 队伍B->move left
09-Mar-24 22:48:19 - INFO - 点击[503, 501]
09-Mar-24 22:48:20 - INFO - 等待阶段，是否可能会进入局内战斗：False
09-Mar-24 22:48:21 - INFO - 尝试呼出弹窗
09-Mar-24 22:48:23 - INFO - 尝试清空弹窗
09-Mar-24 22:48:26 - INFO - ocr结果1
09-Mar-24 22:48:26 - INFO - 当前聚焦队伍A
09-Mar-24 22:48:26 - INFO - 执行step:3 action:1 队伍A->move left-up
09-Mar-24 22:48:28 - INFO - 点击[590, 219]
09-Mar-24 22:48:29 - INFO - 等待阶段，是否可能会进入局内战斗：True
09-Mar-24 22:48:35 - INFO - 有开关弹窗效果
09-Mar-24 22:48:35 - INFO - PHASE结束
09-Mar-24 22:48:37 - INFO - 等待阶段，是否可能会进入局内战斗：True
09-Mar-24 22:48:44 - INFO - 有开关弹窗效果
09-Mar-24 22:48:44 - INFO - H7-1.json执行完毕
09-Mar-24 22:48:44 - INFO - 判断任务GridQuest执行结果是否可控
09-Mar-24 22:49:04 - WARNING - run_until exceeded max times
09-Mar-24 22:49:04 - WARNING - 任务GridQuest执行后条件不成立或超时
09-Mar-24 22:49:04 - INFO - 尝试返回主页
09-Mar-24 22:49:05 - WARNING - 试图点击的目标图像不存在: ./DATA/assets_jp/BUTTON/BUTTON_HOME_ICON.png
09-Mar-24 22:49:08 - WARNING - 试图点击的目标图像不存在: ./DATA/assets_jp/BUTTON/BUTTON_HOME_ICON.png
09-Mar-24 22:49:12 - WARNING - 试图点击的目标图像不存在: ./DATA/assets_jp/BUTTON/BUTTON_HOME_ICON.png
09-Mar-24 22:49:15 - WARNING - run_until exceeded max times
09-Mar-24 22:49:15 - ERROR - 返回主页失败
Traceback (most recent call last):
  File "main.py", line 55, in <module>
  File "BAAH.py", line 187, in BAAH_main
  File "modules\AllTask\myAllTask.py", line 70, in run
  File "modules\AllTask\Task.py", line 54, in run
  File "modules\AllTask\InQuest\InQuest.py", line 57, in on_run
  File "modules\AllTask\Task.py", line 54, in run
  File "modules\AllTask\InQuest\PushQuest.py", line 156, in on_run
  File "modules\AllTask\Task.py", line 61, in run
Exception: 任务GridQuest执行后条件不成立或超时，且无法正确返回主页，程序退出
+======================================BAAH====================================== +
||                                 Version: 1.3.5                                 ||
||                  Bilibili: https://space.bilibili.com/7331920                  ||
||                  Github: https://github.com/sanmusen214/BAAH                   ||
||                                 QQ群: 441069156                                 ||
||                                                                                ||
+================================================================================+

程序运行结束，如有问题请加群(441069156)反馈，在Github上检查下是否有版本更新
https://github.com/sanmusen214/BAAH
出现错误，按回车键退出:
```

观察问题出在```点击[1104, 770]```这类指令时实际上并未点击导致错误进入下一回合

**Comment by sanmusen214** [comment]
我试了一下日服困难7-1推图没有问题，估计是因为网络或者游戏卡顿了导致点击没有点到，你可以尝试把点击后等待时间稍微设长一点。
