### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters 

### ISSUE THREAD

**Issue by somnaewq** [sanmusen214/BAAH#65]
When I press execute in 1.5.1 I get the following error, 1.4.11 still works for me

```
使用语言/Use language:  en_US
2024-07-11 13:52:45.2121084 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
{'OPEN_IN_WEB': True}
NiceGUI ready to go on http://localhost:8001
RUN
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "modules\utils\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "modules\utils\adb_utils.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "modules\utils\log_utils.py", line 86, in <module>
  File "modules\utils\log_utils.py", line 24, in __init__
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "modules\utils\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "modules\utils\adb_utils.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "modules\utils\log_utils.py", line 86, in <module>
  File "modules\utils\log_utils.py", line 24, in __init__
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 51, in <module>
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 21-27: character maps to <undefined>
[25200] Failed to execute script 'main' due to unhandled exception!
Process finished.

```

**Comment by somnaewq** [comment]
Yes, running directly from BAAH.exe works.

**Comment by sanmusen214** [comment]
> Yes, running directly from BAAH.exe works.

OK, I will add another button in GUI to run BAAH in a new terminal (just like before in 1.4.11).

**Comment by sanmusen214** [comment]
You can download [1.5.2](https://github.com/sanmusen214/BAAH/releases/tag/BAAH1.5.2) and find "save and execute (terminal)” button in the gui. 
Please leave this issue open, I'm figuring on proper encoding method of running BAAH in GUI.

**Comment by sanmusen214** [comment]
@somnaewq Hi, can you try to click 'Execute in GUI' button of version [1.8.0](https://github.com/sanmusen214/BAAH/releases/tag/BAAH1.8.0) and see if it works

**Comment by sanmusen214** [comment]
Hi @somnaewq, can you update to version [1.8.1](https://github.com/sanmusen214/BAAH/releases/tag/BAAH1.8.1) and check that if running BAAH in GUI works in your computer now?

**Comment by somnaewq** [comment]
> Hi @somnaewq, can you update to version [1.8.1](https://github.com/sanmusen214/BAAH/releases/tag/BAAH1.8.1) and check that if running BAAH in GUI works in your computer now?

Yes it works perfectly now, thank you.
